# Generated by Django 5.1.6 on 2026-05-22 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('exception_rows', models.PositiveIntegerField(default=0)),
                ('report_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'invoice_reconciliation_batch',
            },
        ),
        migrations.CreateModel(
            name='InvoiceReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment_no', models.CharField(blank=True, max_length=120)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('invoice_no', models.CharField(blank=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('actual_freight', models.DecimalField(decimal_places=4, max_digits=12)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('EXCEPTION', 'Exception')], default='UNMATCHED', max_length=20)),
                ('variance_type', models.CharField(choices=[('OVERCHARGE', 'Overcharge'), ('UNDERCHARGE', 'Undercharge'), ('OK', 'OK'), ('UNMATCHED', 'Unmatched')], default='UNMATCHED', max_length=20)),
                ('dispute_recommended', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'invoice_reconciliation_item',
            },
        ),
        migrations.CreateModel(
            name='QuoteTraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ELIGIBILITY', 'Eligibility'), ('CALCULATION', 'Calculation'), ('API', 'API'), ('ADJUSTMENT', 'Adjustment'), ('NOT_AVAILABLE', 'Not Available'), ('SYSTEM', 'System')], default='CALCULATION', max_length=40)),
                ('step', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('details_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'quote_trace_log',
            },
        ),
        migrations.AlterModelOptions(
            name='quotechargeline',
            options={'verbose_name': 'Quote result breakdown', 'verbose_name_plural': 'Quote result breakdowns'},
        ),
        migrations.RemoveIndex(
            model_name='ratecard',
            name='freight_rat_carrier_dd101e_idx',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='consignment_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rate_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rate_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historicalorder',
            index=models.Index(fields=['consignment_no'], name='freight_his_consign_facc98_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['carrier', 'status', 'is_active'], name='freight_rat_carrier_deb331_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['priority', 'effective_from'], name='freight_rat_priorit_e5fe64_idx'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrier'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='freight.invoicereconciliationbatch'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrier'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.historicalorder'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='quote_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.quotecandidate'),
        ),
        migrations.AddField(
            model_name='quotetracelog',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_logs', to='freight.quotecandidate'),
        ),
        migrations.AddField(
            model_name='quotetracelog',
            name='quote_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_logs', to='freight.quoterun'),
        ),
        migrations.AddIndex(
            model_name='invoicereconciliationitem',
            index=models.Index(fields=['batch', 'match_status', 'variance_type'], name='invoice_rec_batch_i_0a0349_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicereconciliationitem',
            index=models.Index(fields=['order_no', 'consignment_no'], name='invoice_rec_order_n_9afb36_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetracelog',
            index=models.Index(fields=['quote_run', 'candidate', 'event_type'], name='quote_trace_quote_r_ac31bf_idx'),
        ),
        migrations.AddIndex(
            model_name='quotetracelog',
            index=models.Index(fields=['step'], name='quote_trace_step_554abf_idx'),
        ),
    ]
