# Generated by Django 5.1.6 on 2026-05-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_invoicereconciliationbatch_invoicereconciliationitem_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quotecandidate',
            new_name='quote_resul_quote_r_1e7c3f_idx',
            old_name='freight_quo_quote_r_2882eb_idx',
        ),
        migrations.AlterModelTable(
            name='quotecandidate',
            table='quote_result',
        ),
        migrations.AlterModelTable(
            name='quotechargeline',
            table='quote_result_breakdown',
        ),
        migrations.AlterModelTable(
            name='quoterun',
            table='quote_request',
        ),
    ]
