# Generated by Django 5.1.6 on 2026-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_rename_freight_quo_quote_r_2882eb_idx_quote_resul_quote_r_1e7c3f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_database',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_schema',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_system',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sku',
            name='source_table',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sku',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='sync_status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['source_system', 'external_updated_at'], name='freight_sku_source__242545_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['last_synced_at'], name='freight_sku_last_sy_27e6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['sync_status'], name='freight_sku_sync_st_66b501_idx'),
        ),
    ]
