# Generated by Django 5.1.6 on 2026-05-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0004_sku_external_updated_at_sku_last_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo_sku', models.CharField(max_length=80)),
                ('component_sku', models.CharField(max_length=80)),
                ('component_qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('combo_title', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('source_system', models.CharField(default='data_raw.erp.hpoms_product_combo', max_length=120)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='combo_source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['is_combo'], name='freight_sku_is_comb_1ea1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='skucombocomponent',
            index=models.Index(fields=['combo_sku', 'active'], name='freight_sku_combo_s_016036_idx'),
        ),
        migrations.AddIndex(
            model_name='skucombocomponent',
            index=models.Index(fields=['component_sku'], name='freight_sku_compone_0b5595_idx'),
        ),
        migrations.AddIndex(
            model_name='skucombocomponent',
            index=models.Index(fields=['source_updated_at'], name='freight_sku_source__50c8ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='skucombocomponent',
            constraint=models.UniqueConstraint(fields=('combo_sku', 'component_sku'), name='uniq_combo_component_sku'),
        ),
    ]
