# Generated by Django 5.1.6 on 2026-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0005_skucombocomponent_sku_combo_source_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='combo_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='combo_type_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='skucombocomponent',
            name='combo_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skucombocomponent',
            name='combo_type_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
