# Generated by Django 5.1.6 on 2026-05-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0006_sku_combo_type_sku_combo_type_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['category'], name='freight_sku_categor_0f4472_idx'),
        ),
    ]
