# Generated by Django 5.1.6 on 2026-05-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0007_sku_category_sku_freight_sku_categor_0f4472_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='company',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='platform',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='legal_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_group_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_group_name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_group_name_zh',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_database',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_platform_type_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_platform_type_name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_platform_type_name_zh',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_schema',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='source_table',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platform',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='sync_status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_database',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_schema',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_table',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sync_status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='telephone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['source_system', 'external_updated_at'], name='freight_pla_source__94206c_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['source_external_id'], name='freight_pla_source__8226b9_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['platform_group_code'], name='freight_pla_platfor_c32d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['source_platform_type_code'], name='freight_pla_source__f574a6_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['last_synced_at'], name='freight_pla_last_sy_0f3653_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['source_system', 'external_updated_at'], name='freight_war_source__14c684_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['source_external_id'], name='freight_war_source__5d7e72_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['last_synced_at'], name='freight_war_last_sy_9de73d_idx'),
        ),
    ]
