# Generated by Django 5.1.6 on 2026-05-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0008_platform_company_platform_external_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='active_api_accounts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='active_quote_rate_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='active_rate_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='lsp_agent_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrier',
            name='lsp_channel_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrier',
            name='lsp_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_database',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_schema',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='carrier',
            name='source_table',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='carrier',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='sync_status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('CARRIER_IMPORT', 'Carrier Import')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['source_system', 'external_updated_at'], name='freight_car_source__27b1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['source_external_id'], name='freight_car_source__57414e_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['lsp_agent_code'], name='freight_car_lsp_age_46a81d_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['lsp_channel_code'], name='freight_car_lsp_cha_234062_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['last_synced_at'], name='freight_car_last_sy_945591_idx'),
        ),
    ]
