# Generated by Django 5.1.6 on 2026-05-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0013_historicalorder_external_shipping_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='carrier_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrierservice'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='source_external_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='carrier_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrierservice'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='source_external_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='source_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('CARRIER_IMPORT', 'Carrier Import'), ('LSP_RATE_TABLE_IMPORT', 'LSP Rate Table Import'), ('INVOICE_SYNC', 'Invoice Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='InvoiceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source_platform', models.CharField(blank=True, max_length=160)),
                ('freight_account', models.CharField(blank=True, max_length=120)),
                ('mapping_method', models.CharField(choices=[('MANUAL', 'Manual'), ('EXACT', 'Exact'), ('HEURISTIC', 'Heuristic'), ('AUTO_CREATED', 'Auto created')], default='HEURISTIC', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('auto_created_carrier', models.BooleanField(default=False)),
                ('auto_created_service', models.BooleanField(default=False)),
                ('source_system', models.CharField(blank=True, max_length=120)),
                ('source_database', models.CharField(blank=True, max_length=80)),
                ('source_schema', models.CharField(blank=True, max_length=80)),
                ('source_header_table', models.CharField(blank=True, max_length=120)),
                ('source_detail_table', models.CharField(blank=True, max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_sources', to='freight.carrier')),
                ('carrier_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_sources', to='freight.carrierservice')),
            ],
        ),
        migrations.AddField(
            model_name='invoicereconciliationbatch',
            name='invoice_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.invoicesource'),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='invoice_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.invoicesource'),
        ),
        migrations.AddIndex(
            model_name='invoicereconciliationbatch',
            index=models.Index(fields=['invoice_source', 'status'], name='invoice_rec_invoice_1244ac_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicereconciliationbatch',
            index=models.Index(fields=['source_system', 'source_external_id'], name='invoice_rec_source__09df28_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicereconciliationitem',
            index=models.Index(fields=['invoice_source', 'invoice_date'], name='invoice_rec_invoice_fb0c3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicereconciliationitem',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_external_id', ''), _negated=True)), fields=('source_system', 'source_external_id'), name='uniq_invoice_item_source_external'),
        ),
        migrations.AddIndex(
            model_name='invoicesource',
            index=models.Index(fields=['source_platform', 'freight_account'], name='freight_inv_source__9d9175_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesource',
            index=models.Index(fields=['carrier', 'carrier_service'], name='freight_inv_carrier_667258_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesource',
            index=models.Index(fields=['source_system', 'last_synced_at'], name='freight_inv_source__7d38fd_idx'),
        ),
    ]
