# Generated by Django 5.1.6 on 2026-05-29 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0014_invoicereconciliationbatch_carrier_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_external_id', models.CharField(blank=True, max_length=120)),
                ('tracking_no', models.CharField(max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('carrier_channel', models.CharField(blank=True, max_length=160)),
                ('service_provider', models.CharField(blank=True, max_length=160)),
                ('carrier_channel_account', models.CharField(blank=True, max_length=120)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('warehouse_owner_code', models.CharField(blank=True, max_length=80)),
                ('package_no', models.CharField(blank=True, max_length=120)),
                ('purchase_sku', models.CharField(blank=True, max_length=120)),
                ('owner_purchase_sku', models.CharField(blank=True, max_length=120)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='freight.historicalorder')),
            ],
            options={
                'indexes': [models.Index(fields=['tracking_no'], name='freight_his_trackin_4589b1_idx'), models.Index(fields=['carrier_name', 'carrier_channel'], name='freight_his_carrier_dc8bff_idx'), models.Index(fields=['order', 'tracking_no'], name='freight_his_order_i_06ea1d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_external_id', ''), _negated=True), fields=('order', 'source_external_id'), name='uniq_order_shipment_source_external')],
            },
        ),
    ]
