# Generated by Django 5.1.6 on 2026-05-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0015_historicalordershipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpShipmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=160)),
                ('source_external_id', models.CharField(blank=True, max_length=160)),
                ('tracking_no', models.CharField(max_length=120)),
                ('erp_order_no', models.CharField(blank=True, max_length=120)),
                ('erp_owner_order_no', models.CharField(blank=True, max_length=120)),
                ('third_party_order_no', models.CharField(blank=True, max_length=160)),
                ('platform_order_no', models.CharField(blank=True, max_length=160)),
                ('platform_code', models.CharField(blank=True, max_length=80)),
                ('platform_name', models.CharField(blank=True, max_length=160)),
                ('platform_company', models.CharField(blank=True, max_length=160)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('carrier_channel', models.CharField(blank=True, max_length=160)),
                ('service_provider', models.CharField(blank=True, max_length=160)),
                ('carrier_channel_account', models.CharField(blank=True, max_length=120)),
                ('shipping_option', models.CharField(blank=True, max_length=160)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('estimate_source', models.CharField(blank=True, max_length=80)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_shipment_snapshots', to='freight.historicalorder')),
            ],
            options={
                'db_table': 'erp_shipment_snapshot',
            },
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='erp_shipment_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.erpshipmentsnapshot'),
        ),
        migrations.CreateModel(
            name='InvoiceChargeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=160)),
                ('source_external_id', models.CharField(blank=True, max_length=180)),
                ('source_key', models.CharField(blank=True, max_length=80)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('invoice_no', models.CharField(blank=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('order_reference', models.CharField(blank=True, max_length=160)),
                ('source_platform', models.CharField(blank=True, max_length=160)),
                ('freight_account', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('service_name', models.CharField(blank=True, max_length=160)),
                ('charge_type', models.CharField(blank=True, max_length=160)),
                ('amount_basis', models.CharField(blank=True, max_length=40)),
                ('actual_freight', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_line_count', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('invoice_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_snapshots', to='freight.invoicesource')),
            ],
            options={
                'db_table': 'invoice_charge_snapshot',
            },
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='invoice_charge_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.invoicechargesnapshot'),
        ),
        migrations.AddIndex(
            model_name='erpshipmentsnapshot',
            index=models.Index(fields=['tracking_no'], name='erp_shipmen_trackin_76edb1_idx'),
        ),
        migrations.AddIndex(
            model_name='erpshipmentsnapshot',
            index=models.Index(fields=['carrier_name', 'carrier_channel'], name='erp_shipmen_carrier_415a15_idx'),
        ),
        migrations.AddIndex(
            model_name='erpshipmentsnapshot',
            index=models.Index(fields=['platform_code', 'order_date'], name='erp_shipmen_platfor_d6af5e_idx'),
        ),
        migrations.AddIndex(
            model_name='erpshipmentsnapshot',
            index=models.Index(fields=['source_system', 'source_updated_at'], name='erp_shipmen_source__821e70_idx'),
        ),
        migrations.AddConstraint(
            model_name='erpshipmentsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_external_id', ''), _negated=True)), fields=('source_system', 'source_external_id'), name='uniq_erp_ship_snapshot_source'),
        ),
        migrations.AddIndex(
            model_name='invoicechargesnapshot',
            index=models.Index(fields=['tracking_no'], name='invoice_cha_trackin_2aafac_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechargesnapshot',
            index=models.Index(fields=['source_key', 'invoice_date'], name='invoice_cha_source__3f004b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechargesnapshot',
            index=models.Index(fields=['invoice_no'], name='invoice_cha_invoice_ceb92a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicechargesnapshot',
            index=models.Index(fields=['invoice_source'], name='invoice_cha_invoice_8101a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicechargesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_external_id', ''), _negated=True)), fields=('source_system', 'source_external_id'), name='uniq_invoice_charge_snapshot_source'),
        ),
    ]
