# Generated by Django 5.1.6 on 2026-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0016_erpshipmentsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='system_estimate_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='system_estimated_freight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='system_variance_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='system_variance_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
