# Generated by Django 5.1.6 on 2026-05-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0017_invoicereconciliationitem_system_estimate_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightAuditRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=120)),
                ('source_external_id', models.CharField(blank=True, max_length=180)),
                ('calculation_mode', models.CharField(choices=[('ORDER', 'Order'), ('CONSIGNMENT', 'Consignment'), ('ITEM', 'Item')], default='CONSIGNMENT', max_length=20)),
                ('order_no', models.CharField(blank=True, max_length=120)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('platform_code', models.CharField(blank=True, max_length=80)),
                ('platform_name', models.CharField(blank=True, max_length=160)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('erp_estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('invoice_actual_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('erp_shipment_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.erpshipmentsnapshot')),
                ('invoice_reconciliation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.invoicereconciliationitem')),
                ('quote_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.quoterun')),
            ],
            options={
                'db_table': 'freight_audit_row',
            },
        ),
        migrations.CreateModel(
            name='FreightAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier_key', models.CharField(blank=True, max_length=80)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('service_name', models.CharField(blank=True, max_length=160)),
                ('provider_type', models.CharField(blank=True, max_length=20)),
                ('availability', models.CharField(blank=True, max_length=20)),
                ('not_available_reason', models.CharField(blank=True, max_length=160)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('surcharge_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fuel_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('adjustment_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_inc_gst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('variance_to_erp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('variance_to_invoice', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrier')),
                ('carrier_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrierservice')),
                ('quote_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.quotecandidate')),
                ('quote_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.quotechannel')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='freight.freightauditrow')),
            ],
            options={
                'db_table': 'freight_audit_result',
            },
        ),
        migrations.AddIndex(
            model_name='freightauditrow',
            index=models.Index(fields=['calculation_mode', 'status'], name='freight_aud_calcula_94bd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='freightauditrow',
            index=models.Index(fields=['order_no', 'tracking_no'], name='freight_aud_order_n_4ffef6_idx'),
        ),
        migrations.AddIndex(
            model_name='freightauditrow',
            index=models.Index(fields=['platform_code', 'warehouse_code'], name='freight_aud_platfor_da2e0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightauditrow',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_external_id', ''), _negated=True)), fields=('source_system', 'source_external_id', 'calculation_mode'), name='uniq_freight_audit_row_source_mode'),
        ),
        migrations.AddIndex(
            model_name='freightauditresult',
            index=models.Index(fields=['carrier_key', 'availability'], name='freight_aud_carrier_631a92_idx'),
        ),
        migrations.AddIndex(
            model_name='freightauditresult',
            index=models.Index(fields=['quote_channel', 'availability'], name='freight_aud_quote_c_d0c9c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightauditresult',
            constraint=models.UniqueConstraint(fields=('row', 'quote_channel'), name='uniq_freight_audit_row_channel'),
        ),
    ]
