# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freight", "0018_freightauditrow_freightauditresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local account"),
                    ("ENTRA", "Microsoft Entra"),
                    ("HYBRID", "Local + Microsoft Entra"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="entra_tid",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="entra_upn",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_auth_source",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="permission_overrides",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="require_password_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email"], name="freight_use_email_278642_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role", "is_active"], name="freight_use_role_32f1f1_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["auth_provider"], name="freight_use_auth_pr_8a6454_idx"),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                condition=~models.Q(entra_oid=""),
                fields=("entra_oid",),
                name="uniq_userprofile_entra_oid",
            ),
        ),
    ]
