# Generated by Django 5.1.6 on 2026-06-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0019_userprofile_access_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('CARRIER_IMPORT', 'Carrier Import'), ('LSP_RATE_TABLE_IMPORT', 'LSP Rate Table Import'), ('LSP_API_QUOTE_SYNC', 'LSP API Quote Sync'), ('INVOICE_SYNC', 'Invoice Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='LspApiQuoteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=160)),
                ('source_external_id', models.CharField(max_length=120)),
                ('quote_task_id', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=160)),
                ('quote_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('status_summary', models.CharField(blank=True, max_length=255)),
                ('quote_at', models.DateTimeField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('lsp_order_code', models.CharField(blank=True, max_length=160)),
                ('lsp_shipment_code', models.CharField(blank=True, max_length=160)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('strategy_code', models.CharField(blank=True, max_length=120)),
                ('booking_tracking_no', models.CharField(blank=True, max_length=120)),
                ('booking_carrier_code', models.CharField(blank=True, max_length=120)),
                ('booking_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('erp_order_no', models.CharField(blank=True, max_length=160)),
                ('erp_owner_order_no', models.CharField(blank=True, max_length=160)),
                ('external_order_no', models.CharField(blank=True, max_length=160)),
                ('platform_order_no', models.CharField(blank=True, max_length=160)),
                ('source_order_id', models.CharField(blank=True, max_length=120)),
                ('source_platform_id', models.CharField(blank=True, max_length=120)),
                ('erp_estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('erp_postage_estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('predicted_carrier_code', models.CharField(blank=True, max_length=120)),
                ('predicted_carrier_name', models.CharField(blank=True, max_length=160)),
                ('predicted_service_code', models.CharField(blank=True, max_length=120)),
                ('predicted_service_name', models.CharField(blank=True, max_length=160)),
                ('predicted_shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('predicted_carrier_shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('owner_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('predict_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('quote_option_count', models.PositiveIntegerField(default=0)),
                ('destination_suburb', models.CharField(blank=True, max_length=120)),
                ('destination_state', models.CharField(blank=True, max_length=40)),
                ('destination_postcode', models.CharField(blank=True, max_length=20)),
                ('request_summary_json', models.JSONField(blank=True, default=dict)),
                ('response_summary_json', models.JSONField(blank=True, default=dict)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrier')),
                ('historical_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsp_api_quote_snapshots', to='freight.historicalorder')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.platform')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.carrierservice')),
            ],
            options={
                'db_table': 'lsp_api_quote_snapshot',
            },
        ),
        migrations.CreateModel(
            name='LspApiQuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_index', models.PositiveIntegerField(default=0)),
                ('carrier_code', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('courier_code', models.CharField(blank=True, max_length=120)),
                ('courier_name', models.CharField(blank=True, max_length=160)),
                ('service_code', models.CharField(blank=True, max_length=120)),
                ('service_name', models.CharField(blank=True, max_length=160)),
                ('can_shipping', models.BooleanField(default=False)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('carrier_shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('calc_mode', models.CharField(blank=True, max_length=80)),
                ('remark', models.TextField(blank=True)),
                ('raw_quote_json', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='freight.lspapiquotesnapshot')),
            ],
            options={
                'db_table': 'lsp_api_quote_option',
            },
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['historical_order', 'quote_at'], name='freight_lsp_histor_722d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['erp_order_no'], name='freight_lsp_erp_ord_8e5a94_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['external_order_no'], name='freight_lsp_ext_ord_2a8b57_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['platform_order_no'], name='lsp_api_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['booking_tracking_no'], name='lsp_api_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['lsp_order_code', 'lsp_shipment_code'], name='freight_lsp_order_s_c3a413_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquotesnapshot',
            index=models.Index(fields=['predicted_carrier_code'], name='freight_lsp_pred_ca_5560c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='lspapiquotesnapshot',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_external_id'), name='uniq_lsp_api_quote_snapshot_source'),
        ),
        migrations.AddIndex(
            model_name='lspapiquoteoption',
            index=models.Index(fields=['snapshot', 'can_shipping'], name='lsp_api_opt_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='lspapiquoteoption',
            index=models.Index(fields=['courier_code', 'service_code'], name='lsp_api_opt_cour_idx'),
        ),
        migrations.AddConstraint(
            model_name='lspapiquoteoption',
            constraint=models.UniqueConstraint(fields=('snapshot', 'option_index'), name='uniq_lsp_api_quote_option_index'),
        ),
    ]
