# Generated by Django 5.1.6 on 2026-06-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0020_alter_importjob_job_type_lspapiquotesnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('CARRIER_IMPORT', 'Carrier Import'), ('LSP_RATE_TABLE_IMPORT', 'LSP Rate Table Import'), ('LSP_API_QUOTE_SYNC', 'LSP API Quote Sync'), ('LSP_QUOTE_LOG_SYNC', 'LSP Quote Log Sync'), ('INVOICE_SYNC', 'Invoice Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='LspQuoteTaskLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=160)),
                ('source_external_id', models.CharField(max_length=120)),
                ('quote_task_id', models.CharField(blank=True, max_length=120)),
                ('quote_task_job_id', models.CharField(blank=True, max_length=120)),
                ('item_index', models.PositiveIntegerField(default=0)),
                ('item_scope', models.CharField(blank=True, max_length=40)),
                ('log_action', models.CharField(blank=True, max_length=80)),
                ('log_status', models.IntegerField(blank=True, null=True)),
                ('calc_mode', models.CharField(blank=True, max_length=40)),
                ('rate_type', models.CharField(blank=True, max_length=40)),
                ('carrier_agent_code', models.CharField(blank=True, max_length=120)),
                ('carrier_codes', models.TextField(blank=True)),
                ('carrier_strategy_code', models.CharField(blank=True, max_length=120)),
                ('log_created_at', models.DateTimeField(blank=True, null=True)),
                ('log_updated_at', models.DateTimeField(blank=True, null=True)),
                ('agent_code', models.CharField(blank=True, max_length=120)),
                ('carrier_code', models.CharField(blank=True, max_length=120)),
                ('channel_code', models.CharField(blank=True, max_length=120)),
                ('service_level', models.CharField(blank=True, max_length=160)),
                ('can_shipping', models.BooleanField(default=False)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('shipping_cost_with_tax', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('estimated_days', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('raw_item_json', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_log_items', to='freight.lspapiquotesnapshot')),
            ],
            options={
                'db_table': 'lsp_quote_task_log_item',
                'indexes': [models.Index(fields=['snapshot', 'log_action'], name='lsp_log_snapshot_action_idx'), models.Index(fields=['quote_task_id'], name='lsp_log_quote_task_idx'), models.Index(fields=['agent_code', 'carrier_code'], name='lsp_log_agent_carrier_idx'), models.Index(fields=['channel_code', 'service_level'], name='lsp_log_channel_svc_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_external_id', 'item_scope', 'item_index'), name='uniq_lsp_quote_log_item')],
            },
        ),
    ]
