# Generated by Django 5.1.6 on 2026-06-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0023_agent_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrderMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, max_length=160)),
                ('source_external_id', models.CharField(blank=True, max_length=180)),
                ('source_key', models.CharField(blank=True, max_length=80)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('source_table', models.CharField(blank=True, max_length=120)),
                ('invoice_no', models.CharField(blank=True, max_length=120)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('erp_order_id', models.CharField(blank=True, max_length=160)),
                ('erp_order_no', models.CharField(blank=True, max_length=160)),
                ('erp_owner_order_no', models.CharField(blank=True, max_length=160)),
                ('third_party_order_no', models.CharField(blank=True, max_length=160)),
                ('platform_order_no', models.CharField(blank=True, max_length=160)),
                ('warehouse_owner_code', models.CharField(blank=True, max_length=100)),
                ('distribution_owner_code', models.CharField(blank=True, max_length=100)),
                ('carrier_name', models.CharField(blank=True, max_length=160)),
                ('carrier_channel', models.CharField(blank=True, max_length=160)),
                ('carrier_channel_account', models.CharField(blank=True, max_length=120)),
                ('service_name', models.CharField(blank=True, max_length=160)),
                ('match_tier', models.CharField(blank=True, max_length=80)),
                ('match_method', models.CharField(blank=True, max_length=120)),
                ('match_confidence', models.CharField(blank=True, max_length=80)),
                ('match_reason', models.CharField(blank=True, max_length=255)),
                ('amount_ex_gst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amount_inc_gst', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('erp_carrier_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('erp_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('invoice_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_match_snapshots', to='freight.invoicesource')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_order_match_snapshots', to='freight.historicalorder')),
            ],
            options={
                'db_table': 'invoice_order_match_snapshot',
            },
        ),
        migrations.AddField(
            model_name='invoicereconciliationitem',
            name='invoice_order_match_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freight.invoiceordermatchsnapshot'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['tracking_no'], name='invoice_ord_trackin_2fc536_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['invoice_no'], name='invoice_ord_invoice_aab158_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['erp_owner_order_no'], name='invoice_ord_erp_own_f578a0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['third_party_order_no'], name='invoice_ord_third_p_15ae5e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['source_key'], name='invoice_ord_source__44a22f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceordermatchsnapshot',
            index=models.Index(fields=['order'], name='invoice_ord_order_i_bcceb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceordermatchsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_system', ''), _negated=True), models.Q(('source_external_id', ''), _negated=True)), fields=('source_system', 'source_external_id'), name='uniq_invoice_order_match_source'),
        ),
    ]
