# Generated by Django 5.1.6 on 2026-06-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0024_invoiceordermatchsnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicereconciliationitem',
            name='erp_shipment_snapshot',
        ),
        migrations.RemoveField(
            model_name='freightauditrow',
            name='erp_shipment_snapshot',
        ),
        migrations.DeleteModel(
            name='ErpShipmentSnapshot',
        ),
    ]
