# Generated by Django 5.1.6 on 2026-06-25 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0025_remove_invoicereconciliationitem_erp_shipment_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('AGENT_SYNC', 'Agent Sync'), ('CARRIER_IMPORT', 'Carrier Import'), ('LSP_RATE_TABLE_IMPORT', 'LSP Rate Table Import'), ('LSP_API_QUOTE_SYNC', 'LSP API Quote Sync'), ('LSP_BOOKING_ORDER_SYNC', 'LSP Booking Order Sync'), ('LSP_QUOTE_LOG_SYNC', 'LSP Quote Log Sync'), ('INVOICE_SYNC', 'Invoice Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='LspBookingOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=160)),
                ('source_external_id', models.CharField(max_length=120)),
                ('lsp_order_code', models.CharField(blank=True, max_length=160)),
                ('lsp_shipment_code', models.CharField(blank=True, max_length=160)),
                ('reference_no', models.CharField(blank=True, max_length=160)),
                ('customer_reference', models.CharField(blank=True, max_length=160)),
                ('consignment_code', models.CharField(blank=True, max_length=160)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('carrier_code', models.CharField(blank=True, max_length=120)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('calc_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_spread', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('historical_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsp_booking_order_snapshots', to='freight.historicalorder')),
            ],
            options={
                'db_table': 'lsp_booking_order_snapshot',
                'indexes': [models.Index(fields=['tracking_no'], name='lsp_booking_tracking_idx'), models.Index(fields=['historical_order', 'tracking_no'], name='lsp_booking_order_track_idx'), models.Index(fields=['lsp_order_code', 'lsp_shipment_code'], name='lsp_booking_order_ship_idx'), models.Index(fields=['reference_no'], name='lsp_booking_reference_idx'), models.Index(fields=['source_updated_at'], name='lsp_booking_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_external_id'), name='uniq_lsp_booking_order_source')],
            },
        ),
    ]
