# Generated by Django 5.1.6 on 2026-06-25 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0026_alter_importjob_job_type_lspbookingordersnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('ORDER', 'Historical Orders'), ('RATE_CARD', 'Rate Card'), ('LEGACY_SQLSERVER', 'Legacy SQL Server'), ('SKU_SYNC', 'SKU Sync'), ('WAREHOUSE_SYNC', 'Warehouse Sync'), ('PLATFORM_SYNC', 'Platform Sync'), ('AGENT_SYNC', 'Agent Sync'), ('CARRIER_IMPORT', 'Carrier Import'), ('LSP_RATE_TABLE_IMPORT', 'LSP Rate Table Import'), ('LSP_API_QUOTE_SYNC', 'LSP API Quote Sync'), ('LSP_BOOKING_ORDER_SYNC', 'LSP Booking Order Sync'), ('LSP_PACKAGE_ESTIMATE_SYNC', 'LSP Package Estimate Sync'), ('LSP_QUOTE_LOG_SYNC', 'LSP Quote Log Sync'), ('INVOICE_SYNC', 'Invoice Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='LspPackageEstimateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=180)),
                ('source_external_id', models.CharField(max_length=120)),
                ('package_code', models.CharField(max_length=160)),
                ('wms_order_no', models.CharField(blank=True, max_length=160)),
                ('erp_order_no', models.CharField(blank=True, max_length=160)),
                ('warehouse_code', models.CharField(blank=True, max_length=80)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('booking_order_id', models.CharField(blank=True, max_length=120)),
                ('lsp_order_code', models.CharField(blank=True, max_length=160)),
                ('lsp_shipment_code', models.CharField(blank=True, max_length=160)),
                ('reference_no', models.CharField(blank=True, max_length=160)),
                ('customer_reference', models.CharField(blank=True, max_length=180)),
                ('tracking_no', models.CharField(blank=True, max_length=120)),
                ('carrier_code', models.CharField(blank=True, max_length=120)),
                ('package_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('booking_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('predict_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lsp_estimated_freight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('package_weight_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('package_cubic_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_dead_weight', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cubic_m3', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('historical_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsp_package_estimate_snapshots', to='freight.historicalorder')),
            ],
            options={
                'db_table': 'lsp_package_estimate_snapshot',
                'indexes': [models.Index(fields=['package_code'], name='lsp_pkg_package_idx'), models.Index(fields=['tracking_no'], name='lsp_pkg_tracking_idx'), models.Index(fields=['historical_order', 'tracking_no'], name='lsp_pkg_order_track_idx'), models.Index(fields=['erp_order_no'], name='lsp_pkg_erp_order_idx'), models.Index(fields=['lsp_shipment_code'], name='lsp_pkg_shipment_idx'), models.Index(fields=['source_updated_at'], name='lsp_pkg_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_external_id'), name='uniq_lsp_package_est_source')],
            },
        ),
    ]
